staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
local-simulation:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: http://127.0.0.1:18545
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
